### ISSUE TITLE
Разобраться, нужны ли ключи name в мете или хватает названия папки

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/platform#174]
В некоторых статьях ключ есть, в некоторых нет — и всё собирается. Кажется, он не нужен.

Даже так: _лучше бы он был не нужен_ 😉

```yml
title: "Асинхронность в JS"
name: async-in-js
authors:
  - bespoyasov
```
```yml
title: "CSS-анимации"
authors:
  - solarrust
```

Если и правда не нужен, сделаю ПР в контент, который его вычищает.
